-- Exécuté une seule fois au premier démarrage du conteneur PostgreSQL
-- (le dossier /docker-entrypoint-initdb.d n'est lu que si le volume de données
-- est vide). Ce fichier est conservé à titre d'ancre pour d'éventuelles
-- extensions futures, mais le schéma métier n'en réclame aucune :
--   • gen_random_uuid() : core PostgreSQL >= 13
--   • emails case-insensitive : contrainte CHECK + lowercasing applicatif
--   • proximité géographique : Haversine en SQL pur (cf. f_points_relais_proches)
--
-- Toute la suite (tables, vues, fonctions) est posée par les migrations
-- node-pg-migrate dans db/migrations/.
